"""empty message

Revision ID: b5bbd0b06b1a
Revises: fe84b0da1e8b
Create Date: 2024-02-08 12:20:48.286605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bbd0b06b1a'
down_revision = 'fe84b0da1e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
